---
# tasks file for my-iam_role

- name: Create IAM role
  iam:
    iam_type: role
    name: "{{ name }}"
    state: "{{ state }}"
    trust_policy:
      Version: '2012-10-17'
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
